import type { GetStaticPropsContext, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className={styles.grid}>
          <a href="/game/easy" className={styles.card}>
            <h2>入门 &rarr;</h2>
          </a>

          <a href="/game/normal" className={styles.card}>
            <h2>普通 &rarr;</h2>
          </a>

          <a href="/game/difficult" className={styles.card}>
            <h2>困难 &rarr;</h2>
          </a>
        </div>
      </main>
    </div>
  )
}
export async function getStaticProps(context: GetStaticPropsContext) {
  console.log(context)
  return {
    props: {}, // will be passed to the page component as props
  }
}
export default Home
